// types/incident.ts
import { z } from "zod";

// --- Sub-Schemas ---

// Indicator of Compromise (IOC)
export const IocSchema = z.object({
  type: z.enum(["ip", "domain", "hash", "user", "file_path"]).describe("The type of IOC."),
  value: z.string().describe("The identified value (e.g., '192.168.1.1')."),
  confidence: z.number().min(0).max(100).default(75).describe("Confidence score (0-100)."),
});

// Containment Action (Suggested or Executed)
export const SuggestedActionSchema = z.object({
  actionId: z.string().uuid().describe("Unique ID for the suggested action."),
  type: z.enum(["block_ip", "disable_user", "isolate_host", "create_ticket"]).describe("The type of action."),
  target: z.string().describe("The target of the action (e.g., 'user_id', 'ip_address')."),
  justification: z.string().describe("The LLM's justification for the action."),
  kestraFlowId: z.string().optional().describe("The Kestra flow to execute this action."),
});

// --- Primary Incident Schema ---

export const IncidentSchema = z.object({
  // Triage Agent Output fields
  incidentId: z.string().uuid().describe("A unique identifier generated by the agent."),
  title: z.string().describe("A short, descriptive title for the incident (e.g., 'Brute Force Attack on SSH')."),
  severity: z.enum(["Low", "Medium", "High", "Critical", "Informational"]).describe("The calculated severity based on log context."),
  summary: z.string().describe("A concise, human-quality summary of the detected activity."),

  // ADDED: Status field to the Zod Schema
  status: z.enum(["New", "Triaged", "Investigating", "Contained", "Closed"]).default("New").describe("The current status of the incident."),
  logEntryIds: z.array(z.string()).optional().describe('List of LogEntry IDs clustered into this incident (Populated by backend code).'),

  // Investigation/Enrichment fields
  iocs: z.array(IocSchema).describe("List of discovered Indicators of Compromise."),
  mitreTechniques: z.array(z.string()).describe("List of potential MITRE ATT&CK T-Codes."),
  suggestedActions: z.array(SuggestedActionSchema).describe("Automated suggested next steps."),
});

export type Incident = z.infer<typeof IncidentSchema>;